### ISSUE TITLE
feature request: at least once semantic while integrating with datax

### ISSUE THREAD

**Issue by dantengsky** [databendcloud/databend-jdbc#49]
feature-request: at least once semantic while integrating with datax:

in the following case, if databend query returns error during data ingestion, data being ingested should not be dropped.

![img_v2_2a6d4a64-a400-4b46-82c8-4dd2c402b73g_MIDDLE](https://user-images.githubusercontent.com/22081156/228600313-471ed551-6ae1-400f-9780-f1336bb917a5.jpg)

![img_v2_478e9ab6-6a5a-4998-9243-8e84f6be008g_MIDDLE](https://user-images.githubusercontent.com/22081156/228600350-77333c7e-aac5-4537-b1ba-ffb9c0bab299.jpg)

![img_v2_c6db0040-4f42-468e-9e1a-e83476f7e09g_MIDDLE](https://user-images.githubusercontent.com/22081156/228600377-08ab92ff-2cb7-4e4b-adaa-90da2d6ed47e.jpg)

**Comment by hantmac** [comment]
Datax is at least once mode and databend jdbc will retry when if databend query returns error during data ingestion but I found the error it `401` which will not retry in jdbc. And this error seems caused by meta down which is a critical error.

**Comment by yufan022** [comment]
Can we retry or interrupt DataX when encountering this error?

At present, there will be no retry or interruption of the task. This may result in downstream data loss and require checking the logs to discover.

**Comment by hantmac** [comment]
> Can we retry or interrupt DataX when encountering this error?
> 
> At present, there will be no retry or interruption of the task. This may result in downstream data loss and require checking the logs to discover.

I think there is no need to retry on this kind of error because the meta has down.  However, it feels better to have a scheduling system for DataX to work with for stability. For example, after running the verification, if there is any inconsistency, it will delete the data from the previous day and run again until the data is accurate. It is very useful for T+1 data sync.
