### ISSUE TITLE
doc: write flink cdc integration doc

### ISSUE THREAD

**Issue by ZhiHanZ** [databendcloud/databend-jdbc#70]

**Comment by ZhiHanZ** [comment]
I know we have already published the doc, could you append flink CDC integration doc on README reference? cc @hantmac

**Comment by hantmac** [comment]
> I know we have already published the doc, could you append flink CDC integration doc on README reference? cc @hantmac

Eric will give an EN version and I will add it to README after that.

**Comment by hantmac** [comment]
https://databend.rs/doc/load-data/load-db/flink-cdc
