### ISSUE TITLE
Statement in DatabendDatabaseMetaData is not closed

### ISSUE THREAD

**Issue by cdmikechen** [databendcloud/databend-jdbc#83]
When calling the resultset, `DatabendDatabaseMetaData` does not currently look like closing the statement:

https://github.com/databendcloud/databend-jdbc/blob/15aeecb72285022d14cbecd9190933fb27c7789c/databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java#L1622-1651
```java
    private ResultSet select(String sql)
            throws SQLException
    {
        Statement statement = getConnection().createStatement();
        DatabendResultSet resultSet;
        try {
            resultSet = (DatabendResultSet) statement.executeQuery(sql);
        }
        catch (Throwable e) {
            try {
                statement.close();
            }
            catch (Throwable closeException) {
                if (closeException != e) {
                    e.addSuppressed(closeException);
                }
            }

            throw e;
        }
        return (ResultSet) resultSet;
    }
```

In `DatabendStatement`, closing the `Statement` will close the http-client, so that closing the `Statement` operation I personally feel is still needed.
But closing the `Statement` will also close the related `ResultSet`, according to the logical processing, the `ResultSet` needs to be returned to the user for iterator, so it can't be closed directly.

```java
    @Override
    public void close()
            throws SQLException
    {
        DatabendConnection connection = this.connection.getAndSet(null);
        if (connection == null) {
            return;
        }
        onClose.accept(this);
        DatabendClient client = executingClient.get();
        if (client != null) {
            client.close();
        }
        closeResultSet();
    }
```

This will lead to a conflict problem, should we inject a callback method on the `ResultSet`, the `ResultSet` returned by `DatabendDatabaseMetaData` will automatically close the `Statement` when it is closed?

**Comment by hantmac** [comment]
HI @cdmikechen , The try-with-resources statement is a try statement that declares one or more resources. A resource is an object that must be closed after the program is finished with it. The try-with-resources statement ensures that each resource is closed at the end of the statement. Any object that implements java.lang.AutoCloseable, which includes all objects which implement java.io.Closeable, can be used as a resource. More details see https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by hantmac** [comment]
@cdmikechen  I think user should call stmt.close after handling the `ResultSet` 🤔

**Comment by cdmikechen** [comment]
@hantmac 
`MetaData` object returns only `ResultSet`, this is the biggest difference between it and jdbc query, example codes are as follows:
```java
try (ResultSet rs = conn.getMetaData().getColumns(this.db, this.schema, this.table, "%")) {
     while (rs.next()) {
        // ....
    }
}
```

**Comment by hantmac** [comment]
> @hantmac `MetaData` object returns only `ResultSet`, this is the biggest difference between it and jdbc query, example codes are as follows:
> 
> ```java
> try (ResultSet rs = conn.getMetaData().getColumns(this.db, this.schema, this.table, "%")) {
>     while (rs.next()) {
>         // ....
>     }
> }
> ```
> 
> One solution I can think of is to first return the data inside the method and then re-wrap a `ResultSet` object. Like mysql jdbc codes: https://github.com/mysql/mysql-connector-j/blob/release/8.x/src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaData.java#L2080-L2284

Make sense. I marked this issue. Or you can make a pr if you would like to 😄

**Comment by cdmikechen** [comment]
@hantmac Sure thing~ 

I'm trying to use databend for cloud data warehouse, and I'm using a lot of metadata inside my current project to do some fields querying and type parsing. So my requirements for jdbc are still high, and there are some related issues that I will modify if I am able to.

I've put some of the issues that I've found in a new created issue https://github.com/databendcloud/databend-jdbc/issues/84, if you have time you can take a look.

Also, I would like to know if batch writes are currently supported by databend-jdbc?

**Comment by hantmac** [comment]
Awesome! @cdmikechen 
You can pick the issue you would to do and assign it to yourself. 

`databend-jdbc` has supported batch write using [insert-with-attachment](https://github.com/databendcloud/databend-jdbc/blob/main/databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java#L301). It's has high efficency.
