### ISSUE TITLE
TABLE_TYPE needs to be returned and defined according to the jdbc standard

### ISSUE THREAD

**Issue by cdmikechen** [databendcloud/databend-jdbc#86]
`TABLE_TYPE` is currently returned as `BASE TABLE` in databend, but in the java jdbc standard, the return value should be `TABLE`.

https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getTableTypes--

I copy part of the source codes in `java.sql.DatabaseMetaData`:

```java
    /**
     * Retrieves the table types available in this database.  The results
     * are ordered by table type.
     *
     * <P>The table type is:
     *  <OL>
     *  <LI><B>TABLE_TYPE</B> String {@code =>} table type.  Typical types are "TABLE",
     *                  "VIEW", "SYSTEM TABLE", "GLOBAL TEMPORARY",
     *                  "LOCAL TEMPORARY", "ALIAS", "SYNONYM".
     *  </OL>
     *
     * @return a {@code ResultSet} object in which each row has a
     *         single {@code String} column that is a table type
     * @throws SQLException if a database access error occurs
     */
    ResultSet getTableTypes() throws SQLException;
```

MySql related codes:

https://github.com/mysql/mysql-connector-j/blob/7b6f9a337afe6ccb41823df485bf848ca7952b09/src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaData.java#L610-l613
```java
    /**
     * Enumeration for Table Types
     */
    protected enum TableType {
        LOCAL_TEMPORARY("LOCAL TEMPORARY"), SYSTEM_TABLE("SYSTEM TABLE"), SYSTEM_VIEW("SYSTEM VIEW"), TABLE("TABLE", new String[] { "BASE TABLE" }),
        VIEW("VIEW"), UNKNOWN("UNKNOWN");
```

**Comment by hantmac** [comment]
@cdmikechen HI, the table type in databend is define in `information_schema.tables`, you can use `SELECT table_type as table_type FROM information_schema.tables GROUP BY table_type ORDER BY table_type` to get it.  Databend jdbc just get from `databend` directly.  IMHO, we can convert BASE TABLE to TABLE but I will talk with databend developer why databend use BASE TABLE  instead of TABLE.

**Comment by cdmikechen** [comment]
> @cdmikechen HI, the table type in databend is define in `information_schema.tables`, you can use `SELECT table_type as table_type FROM information_schema.tables GROUP BY table_type ORDER BY table_type` to get it. Databend jdbc just get from `databend` directly. IMHO, we can convert BASE TABLE to TABLE but I will talk with databend developer why databend use BASE TABLE instead of TABLE.

@hantmac 
I created a new PR https://github.com/databendcloud/databend-jdbc/pull/91 . 
Using `information_schema.tables` in MySQL returns table type `BASE TABLE` as well, so I don't think the databend server should need to be modified, but rather on the jdbc
